// Copyright (C) 2016 David Reid. See included LICENSE file.

// This file was automatically generated by the pre-build tool. Do not modify.

#define DRED_STOCK_IMAGE_ID_CROSS 0
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT 1
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT_DOWN 2


#define DRED_CONFIG_VARIABLE_DECLARATIONS \
dr_bool32 showTabBar; \
dr_bool32 showMenuBar; \
dr_bool32 autoHideCmdBar; \
dr_bool32 enableAutoReload; \
dr_bool32 useDefaultWindowPos; \
int windowPosX; \
int windowPosY; \
int windowWidth; \
int windowHeight; \
dr_bool32 windowMaximized; \
float uiScale; \
dred_font* pUIFont; \
dred_color cmdbarBGColor; \
dred_color cmdbarBGColorActive; \
dred_font* pCmdbarTBFont; \
dred_color cmdbarTextColor; \
dred_color cmdbarTextColorActive; \
float cmdbarPaddingX; \
float cmdbarPaddingY; \
dred_color tabgroupBGColor; \
dred_color tabBGColorInvactive; \
dred_color tabBGColorActive; \
dred_color tabBGColorHovered; \
dred_font* tabFont; \
dred_color tabTextColor; \
dred_color tabTextColorActive; \
dred_color tabTextColorHovered; \
float tabPadding; \
dr_bool32 tabShowCloseButton; \
dred_color tabCloseButtonColor; \
dred_font* pTextEditorFont; \
dred_color textEditorTextColor; \
dred_color textEditorBGColor; \
dred_color textEditorCursorColor; \
float textEditorCursorWidth; \
dred_color textEditorSelectionBGColor; \
dred_color textEditorActiveLineColor; \
dr_bool32 textEditorShowLineNumbers; \
dred_color textEditorLineNumbersColor; \
dred_color textEditorLineNumbersBGColor; \
float textEditorLineNumbersPadding; \
dred_color textEditorSBTrackColor; \
dred_color textEditorSBThumbColor; \
dred_color textEditorSBThumbColorHovered; \
dred_color textEditorSBThumbColorPressed; \
float textEditorSBSize; \
dr_bool32 textEditorShowScrollbarHorz; \
dr_bool32 textEditorShowScrollbarVert; \
dr_bool32 textEditorEnableExcessScrolling; \
dr_bool32 textEditorTabsToSpacesEnabled; \
int textEditorTabSizeInSpaces; \
float textEditorScale; \
dr_bool32 textEditorEnableAutoIndent; \
dr_bool32 textEditorEnableWordWrap; \
dr_bool32 textEditorEnableDragAndDrop; \
dred_color cppCommentTextColor; \
dred_color cppStringTextColor; \
dred_color cppKeywordTextColor;


#define DRED_MENU_ITEM_ID_NONE 0
#define DRED_MENU_ITEM_ID_SEPARATOR 1
#define DRED_MENU_ITEM_ID_GENERIC_HELP_ABOUT 2
#define DRED_MENU_ITEM_ID_GENERIC_SETTINGS_THEMES_DARK 3
#define DRED_MENU_ITEM_ID_GENERIC_SETTINGS_THEMES_LIGHT 4
#define DRED_MENU_ITEM_ID_GENERIC_SETTINGS_THEMES 5
#define DRED_MENU_ITEM_ID_GENERIC_SETTINGS_SETTINGS 6
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_FILE_NEW 7
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_FILE_OPEN 8
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_FILE_OPEN_RECENT 9
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_FILE_OPEN_FAVOURITE 10
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_FILE_EXIT 11
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_FILE 12
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_VIEW 13
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_SETTINGS 14
#define DRED_MENU_ITEM_ID_NOTHINGOPEN_HELP 15
#define DRED_MENU_ITEM_ID_TEXT_FILE_NEW 16
#define DRED_MENU_ITEM_ID_TEXT_FILE_OPEN 17
#define DRED_MENU_ITEM_ID_TEXT_FILE_OPEN_RECENT 18
#define DRED_MENU_ITEM_ID_TEXT_FILE_OPEN_FAVOURITE 19
#define DRED_MENU_ITEM_ID_TEXT_FILE_ADDFAVOURITE 20
#define DRED_MENU_ITEM_ID_TEXT_FILE_REMOVEFAVOURITE 21
#define DRED_MENU_ITEM_ID_TEXT_FILE_SAVE 22
#define DRED_MENU_ITEM_ID_TEXT_FILE_SAVEAS 23
#define DRED_MENU_ITEM_ID_TEXT_FILE_SAVEALL 24
#define DRED_MENU_ITEM_ID_TEXT_FILE_CLOSE 25
#define DRED_MENU_ITEM_ID_TEXT_FILE_CLOSEALL 26
#define DRED_MENU_ITEM_ID_TEXT_FILE_PRINT 27
#define DRED_MENU_ITEM_ID_TEXT_FILE_EXIT 28
#define DRED_MENU_ITEM_ID_TEXT_EDIT_UNDO 29
#define DRED_MENU_ITEM_ID_TEXT_EDIT_REDO 30
#define DRED_MENU_ITEM_ID_TEXT_EDIT_CUT 31
#define DRED_MENU_ITEM_ID_TEXT_EDIT_COPY 32
#define DRED_MENU_ITEM_ID_TEXT_EDIT_PASTE 33
#define DRED_MENU_ITEM_ID_TEXT_EDIT_DELETE 34
#define DRED_MENU_ITEM_ID_TEXT_EDIT_SELECTALL 35
#define DRED_MENU_ITEM_ID_TEXT_VIEW_TABBARS 36
#define DRED_MENU_ITEM_ID_TEXT_VIEW_CMDBAR 37
#define DRED_MENU_ITEM_ID_TEXT_VIEW_LINENUMBERS 38
#define DRED_MENU_ITEM_ID_TEXT_VIEW_RESETZOOM 39
#define DRED_MENU_ITEM_ID_TEXT_VIEW_WORDWRAP 40
#define DRED_MENU_ITEM_ID_TEXT_FIND_FIND 41
#define DRED_MENU_ITEM_ID_TEXT_FIND_REPLACE 42
#define DRED_MENU_ITEM_ID_TEXT_FIND_GOTO 43
#define DRED_MENU_ITEM_ID_TEXT_FILE 44
#define DRED_MENU_ITEM_ID_TEXT_EDIT 45
#define DRED_MENU_ITEM_ID_TEXT_VIEW 46
#define DRED_MENU_ITEM_ID_TEXT_FIND 47
#define DRED_MENU_ITEM_ID_TEXT_SETTINGS 48
#define DRED_MENU_ITEM_ID_TEXT_HELP 49
#define DRED_MENU_ITEM_ID_TEXT_POPUP_UNDO 50
#define DRED_MENU_ITEM_ID_TEXT_POPUP_REDO 51
#define DRED_MENU_ITEM_ID_TEXT_POPUP_CUT 52
#define DRED_MENU_ITEM_ID_TEXT_POPUP_COPY 53
#define DRED_MENU_ITEM_ID_TEXT_POPUP_PASTE 54
#define DRED_MENU_ITEM_ID_TEXT_POPUP_DELETE 55
#define DRED_MENU_ITEM_ID_TEXT_POPUP_SELECTALL 56
#define DRED_MENU_ITEM_ID_TABPOPUP_SAVE 57
#define DRED_MENU_ITEM_ID_TABPOPUP_SAVEAS 58
#define DRED_MENU_ITEM_ID_TABPOPUP_SAVEALL 59
#define DRED_MENU_ITEM_ID_TABPOPUP_CLOSE 60
#define DRED_MENU_ITEM_ID_TABPOPUP_CLOSEALL 61
#define DRED_MENU_ITEM_ID_TABPOPUP_ADDFAVOURITE 62
#define DRED_MENU_ITEM_ID_TABPOPUP_REMOVEFAVOURITE 63

typedef struct
{
    dtk_menu genericHelp;
    dtk_menu genericSettingsThemes;
    dtk_menu genericSettings;
    dtk_menu recentfiles;
    dtk_menu favouritefiles;
    dtk_menu nothingopenFile;
    dtk_menu nothingopenView;
    dtk_menu nothingopen;
    dtk_menu textFile;
    dtk_menu textEdit;
    dtk_menu textView;
    dtk_menu textFind;
    dtk_menu text;
    dtk_menu textPopup;
    dtk_menu tabpopup;
} dred_stock_menus;

