// Copyright (C) 2016 David Reid. See included LICENSE file.

// This file was automatically generated by the pre-build tool. Do not modify.

#define DRED_STOCK_IMAGE_ID_CROSS 0
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT 1
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT_DOWN 2


#define DRED_CONFIG_VARIABLE_DECLARATIONS \
drBool32 showTabBar; \
drBool32 showMenuBar; \
drBool32 autoHideCmdBar; \
drBool32 enableAutoReload; \
drBool32 useDefaultWindowPos; \
int windowPosX; \
int windowPosY; \
int windowWidth; \
int windowHeight; \
drBool32 windowMaximized; \
float uiScale; \
dred_font* pUIFont; \
dred_color cmdbarBGColor; \
dred_color cmdbarBGColorActive; \
dred_font* pCmdbarTBFont; \
dred_color cmdbarTextColor; \
dred_color cmdbarTextColorActive; \
float cmdbarPaddingX; \
float cmdbarPaddingY; \
dred_color tabgroupBGColor; \
dred_color tabBGColorInvactive; \
dred_color tabBGColorActive; \
dred_color tabBGColorHovered; \
dred_font* tabFont; \
dred_color tabTextColor; \
dred_color tabTextColorActive; \
dred_color tabTextColorHovered; \
float tabPadding; \
drBool32 tabShowCloseButton; \
dred_color tabCloseButtonColor; \
dred_font* pTextEditorFont; \
dred_color textEditorTextColor; \
dred_color textEditorBGColor; \
dred_color textEditorCursorColor; \
float textEditorCursorWidth; \
dred_color textEditorSelectionBGColor; \
dred_color textEditorActiveLineColor; \
drBool32 textEditorShowLineNumbers; \
dred_color textEditorLineNumbersColor; \
dred_color textEditorLineNumbersBGColor; \
float textEditorLineNumbersPadding; \
dred_color textEditorSBTrackColor; \
dred_color textEditorSBThumbColor; \
dred_color textEditorSBThumbColorHovered; \
dred_color textEditorSBThumbColorPressed; \
float textEditorSBSize; \
drBool32 textEditorShowScrollbarHorz; \
drBool32 textEditorShowScrollbarVert; \
drBool32 textEditorEnableExcessScrolling; \
drBool32 textEditorTabsToSpacesEnabled; \
int textEditorTabSizeInSpaces; \
float textEditorScale; \
drBool32 textEditorEnableAutoIndent; \
drBool32 textEditorEnableWordWrap; \
drBool32 textEditorEnableDragAndDrop; \
dred_color cppCommentTextColor; \
dred_color cppStringTextColor; \
dred_color cppKeywordTextColor;
