// Copyright (C) 2016 David Reid. See included LICENSE file.

// This file was automatically generated by the pre-build tool. Do not modify.

#define DRED_STOCK_IMAGE_ID_CROSS 0
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT 1
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT_DOWN 2


#define DRED_CONFIG_VARIABLE_DECLARATIONS \
bool showTabBar; \
bool showMenuBar; \
bool autoHideCmdBar; \
bool enableAutoReload; \
bool useDefaultWindowPos; \
int windowPosX; \
int windowPosY; \
int windowWidth; \
int windowHeight; \
bool windowMaximized; \
float uiScale; \
dred_font* pUIFont; \
dred_color cmdbarBGColor; \
dred_color cmdbarBGColorActive; \
dred_font* pCmdbarTBFont; \
dred_color cmdbarTextColor; \
dred_color cmdbarTextColorActive; \
float cmdbarPaddingX; \
float cmdbarPaddingY; \
dred_color tabgroupBGColor; \
dred_color tabBGColorInvactive; \
dred_color tabBGColorActive; \
dred_color tabBGColorHovered; \
dred_font* tabFont; \
dred_color tabTextColor; \
dred_color tabTextColorActive; \
dred_color tabTextColorHovered; \
float tabPadding; \
bool tabShowCloseButton; \
dred_color tabCloseButtonColor; \
dred_font* pTextEditorFont; \
dred_color textEditorTextColor; \
dred_color textEditorBGColor; \
dred_color textEditorCursorColor; \
float textEditorCursorWidth; \
dred_color textEditorSelectionBGColor; \
dred_color textEditorActiveLineColor; \
bool textEditorShowLineNumbers; \
dred_color textEditorLineNumbersColor; \
dred_color textEditorLineNumbersBGColor; \
float textEditorLineNumbersPadding; \
dred_color textEditorSBTrackColor; \
dred_color textEditorSBThumbColor; \
dred_color textEditorSBThumbColorHovered; \
dred_color textEditorSBThumbColorPressed; \
float textEditorSBSize; \
bool textEditorShowScrollbarHorz; \
bool textEditorShowScrollbarVert; \
bool textEditorEnableExcessScrolling; \
bool textEditorTabsToSpacesEnabled; \
int textEditorTabSizeInSpaces; \
float textEditorScale; \
bool textEditorEnableAutoIndent; \
bool textEditorEnableWordWrap; \
dred_color cppCommentTextColor; \
dred_color cppStringTextColor; \
dred_color cppKeywordTextColor;
