// Copyright (C) 2016 David Reid. See included LICENSE file.

// Converts a WinMain style command line to argv style.
//
// Returns argc.
//
// Use dtk_free_argv to free the allocated memory.
int dtk_winmain_to_argv(const char* cmdlineWinMain, char*** argvOut);

// Frees the argc/argv command line that was generated by dtk_winmain_to_argv().
void dtk_free_argv(char** argv);