// Copyright (C) 2017 David Reid. See included LICENSE file.

// Converts a WinMain style command line to argv style.
//
// Returns argc.
//
// Use dtk_free_argv to free the allocated memory.
int dtk_winmain_to_argv(const char* cmdlineWinMain, char*** argvOut);

// Frees the argc/argv command line that was generated by dtk_winmain_to_argv().
void dtk_free_argv(char** argv);

// Retrieves the value of a key from an argc/argv style of command line. Do not free the returned value.
char* dtk_argv_get_value(int argc, char** argv, const char* key);