// Copyright (C) 2017 David Reid. See included LICENSE file.

dtk_stock_image_info g_pDTKStockImageInfo[] = {
    // cross.svg
    {   dtk_image_type_vector, 0, 0,
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
        "<svg\n"
        "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n"
        "   xmlns:cc=\"http://creativecommons.org/ns#\"\n"
        "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
        "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns=\"http://www.w3.org/2000/svg\"\n"
        "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n"
        "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n"
        "   version=\"1.1\"\n"
        "   id=\"svg3343\"\n"
        "   viewBox=\"0 0 16 16\"\n"
        "   height=\"16\"\n"
        "   width=\"16\"\n"
        "   inkscape:version=\"0.92.3 (2405546, 2018-03-11)\"\n"
        "   sodipodi:docname=\"cross16.svg\">\n"
        "  <sodipodi:namedview\n"
        "     pagecolor=\"#86ff86\"\n"
        "     bordercolor=\"#666666\"\n"
        "     borderopacity=\"1\"\n"
        "     objecttolerance=\"10\"\n"
        "     gridtolerance=\"10\"\n"
        "     guidetolerance=\"10\"\n"
        "     inkscape:pageopacity=\"0\"\n"
        "     inkscape:pageshadow=\"2\"\n"
        "     inkscape:window-width=\"1920\"\n"
        "     inkscape:window-height=\"1027\"\n"
        "     id=\"namedview12\"\n"
        "     showgrid=\"false\"\n"
        "     inkscape:zoom=\"0.921875\"\n"
        "     inkscape:cx=\"57.496634\"\n"
        "     inkscape:cy=\"79.346395\"\n"
        "     inkscape:window-x=\"-8\"\n"
        "     inkscape:window-y=\"-8\"\n"
        "     inkscape:window-maximized=\"1\"\n"
        "     inkscape:current-layer=\"svg3343\" />\n"
        "  <defs\n"
        "     id=\"defs3345\">\n"
        "    <marker\n"
        "       style=\"overflow:visible\"\n"
        "       id=\"Arrow1Lstart\"\n"
        "       refX=\"0\"\n"
        "       refY=\"0\"\n"
        "       orient=\"auto\">\n"
        "      <path\n"
        "         transform=\"matrix(0.8,0,0,0.8,10,0)\"\n"
        "         style=\"fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1.00000003pt;stroke-opacity:1\"\n"
        "         d=\"M 0,0 5,-5 -12.5,0 5,5 Z\"\n"
        "         id=\"path4157\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "    </marker>\n"
        "    <marker\n"
        "       style=\"overflow:visible\"\n"
        "       id=\"Arrow1Lend\"\n"
        "       refX=\"0\"\n"
        "       refY=\"0\"\n"
        "       orient=\"auto\">\n"
        "      <path\n"
        "         transform=\"matrix(-0.8,0,0,-0.8,-10,0)\"\n"
        "         style=\"fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1.00000003pt;stroke-opacity:1\"\n"
        "         d=\"M 0,0 5,-5 -12.5,0 5,5 Z\"\n"
        "         id=\"path4160\"\n"
        "         inkscape:connector-curvature=\"0\" />\n"
        "    </marker>\n"
        "  </defs>\n"
        "  <metadata\n"
        "     id=\"metadata3348\">\n"
        "    <rdf:RDF>\n"
        "      <cc:Work\n"
        "         rdf:about=\"\">\n"
        "        <dc:format>image/svg+xml</dc:format>\n"
        "        <dc:type\n"
        "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n"
        "        <dc:title></dc:title>\n"
        "      </cc:Work>\n"
        "    </rdf:RDF>\n"
        "  </metadata>\n"
        "  <g\n"
        "     transform=\"matrix(0.0638001,0,0,0.0638001,-0.16641337,-50.9744)\"\n"
        "     id=\"layer1\"\n"
        "     style=\"opacity:1;fill:#ffffff;fill-opacity:1;fill-rule:nonzero;stroke:#ffffff;stroke-opacity:1\">\n"
        "    <path\n"
        "       id=\"path3351\"\n"
        "       d=\"M 25.912089,822.27426 230.08791,1026.4501\"\n"
        "       style=\"fill:#ffffff;fill-opacity:1;fill-rule:nonzero;stroke:#ffffff;stroke-width:46.14142609;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\"\n"
        "       inkscape:connector-curvature=\"0\" />\n"
        "    <path\n"
        "       id=\"path4459\"\n"
        "       d=\"M 230.08791,822.27426 25.912089,1026.4501\"\n"
        "       style=\"fill:#ffffff;fill-opacity:1;fill-rule:nonzero;stroke:#ffffff;stroke-width:46.14142609;stroke-linecap:round;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1\"\n"
        "       inkscape:connector-curvature=\"0\" />\n"
        "  </g>\n"
        "</svg>\n"
    }
};

dtk_stock_image_info* dtk_get_stock_image_info(dtk_uint32 stockImageID)
{
    if (stockImageID >= DTK_STOCK_IMAGE_COUNT) {
        return NULL;
    }

    return &g_pDTKStockImageInfo[stockImageID];
}