// Copyright (C) 2018 David Reid. See included LICENSE file.

// Callback for passing to dtk_argv_parse().
typedef dtk_bool32 dtk_argv_parse_proc(const char* key, const char* value, void* pUserData);

// Converts a WinMain style command line to argv style.
//
// Returns argc.
//
// Use dtk_free_argv to free the allocated memory.
int dtk_winmain_to_argv(const char* cmdlineWinMain, char*** argvOut);

// Frees the argc/argv command line that was generated by dtk_winmain_to_argv().
void dtk_free_argv(char** argv);

// Parses a command line.
//
// The string passed to the "value" parameter of the callback is always set to one of the items in the argv array
// which means it can be used directly without the need to copy.
void dtk_argv_parse(int argc, char** argv, dtk_argv_parse_proc callback, void* pUserData);

// Determines whether of not the given key is present on the command line.
dtk_bool32 dtk_argv_exists(int argc, char** argv, const char* key);

// Retrieves the value of a key from an argc/argv style of command line. Do not free the returned value.
const char* dtk_argv_get_value(int argc, char** argv, const char* key);