// This file was automatically generated by the pre-build tool. Do not modify.

const char g_CommandNamePool[] = 
    "!\0"
    "find\0"
    "find-next\0";

const char* g_CommandNames[] = {
    g_CommandNamePool + 0,
    g_CommandNamePool + 2,
    g_CommandNamePool + 7,
};

dred_command g_Commands[] = {
    {dred_command__system_command, DRED_CMDBAR_RELEASE_KEYBOARD},
    {dred_command__find, DRED_CMDBAR_RELEASE_KEYBOARD},
    {dred_command__find_next, DRED_CMDBAR_NO_CLEAR},
};

#define DRED_COMMAND_COUNT 3