
// All config variables are defined in the section below. The pre-build tool will look at these variables and construct the main
// config struct based on their names and types.

// BEGIN CONFIG VARS
//
// show-tab-bar showTabBar bool true
//   Whether or not to show the tab bar.
//
// show-menu-bar showMenuBar bool true
//   Whether or not to show the menu bar.
//
// auto-hide-cmd-bar autoHideCmdBar bool false
//   Whether or not to show the command bar at all times. If this is set to false it will be shown only when it has keyboard focus.
//
//
// ui-scale uiScale float 1
//   The scale of the UI. The total scale of UI elements is equal to the DPI scaling multiplied by this value.
//
// ui-font pUIFont font system-font-ui
//   The default font to use for general UI elements. This will act as the default font in the event that a font fails to load.
//
//
// cmdbar-bg-color cmdbarBGColor color 64 64 64 
//   The background color of the command bar.
//
// cmdbar-bg-color-active cmdbarBGColorActive color 128 51 0
//   The background color of the command bar while it's got the keyboard focus.
//
// cmdbar-tb-font pCmdbarTBFont font system-font-mono
//   The font to use in the text box of the command bar.
//
// cmdbar-tb-text-color cmdbarTBTextColor color 224 224 224
//   The color of the text in the text box of the command bar.
//
// cmdbar-msg-font pCmdbarMessageFont font system-font-ui
//   The font to use for the message box of the command bar.
//
// cmdbar-padding-horz cmdbarPaddingX float 2
//   The amount of padding to apply to the command bar on the left and right sides.
//
// cmdbar-padding-vert cmdbarPaddingY float 2
//   The amount of padding to apply to the command bar on the top and bottom sides.
//
//
// tabgroup-bg-color tabgroupBGColor color 48 48 48
//   The background color of tab groups. This will be shown when there are no tabs open in the group.
//
// tab-bg-color-inactive tabBGColorInvactive color 58 58 58
//   The background color of tabs while inactive.
//
// tab-bg-color-active tabBGColorActive color 16 92 160
//   The background color of tabs while active.
//
// tab-bg-color-hovered tabBGColorHovered color 32 128 192
//   The background color of tabs while hovered.
//
// tab-font tabFont font system-font-ui
//   The font to use on tabs.
//
// tab-text-color tabTextColor color 224 224 224
//   The color of the text on tabs.
//
// tab-padding tabPadding float 4
//   The amount of padding to apply to all sides of a tab.
//
// tab-show-close-button tabShowCloseButton bool true
//   Whether or not to show the close button on tabs.
//
//
// texteditor-font pTextEditorFont font system-font-mono
//   The font to use in text editors.
//
// texteditor-text-color textEditorTextColor color 224 224 224
//   The base color of the text in a text editor. Note that syntax highlighting is independant of this variable.
//
// texteditor-bg-color textEditorBGColor color 48 48 48
//   The background color to use in text editors.
//
// texteditor-cursor-color textEditorCursorColor color 224 224 224
//   The color of the caret/cursor in text editors.
//
// texteditor-cursor-width textEditorCursorWidth float 1
//   The thickness of the caret/cursor in text editors.
//
// texteditor-selection-bg-color textEditorSelectionBGColor color 64 128 192
//   The background color to use for selected text.
//
// texteditor-active-line-color textEditorActiveLineColor color 40 40 40
//   The background color of the line that the caret is currently sitting on in a text editor.
//
// texteditor-line-numbers-color textEditorLineNumbersColor color 80 160 192
//   The color of the line numbers text.
//
// texteditor-line-numbers-bg-color textEditorLineNumbersBGColor color 48 48 48
//   The color of the background of the line numbers.
//
// texteditor-line-numbers-padding textEditorLineNumbersPadding float 16
//   The padding between the line numbers and the text in the text editor.
//
// END CONFIG VARS

typedef struct
{
    // The main context that owns this config. This is set to the context that initialized the config object.
    dred_context* pDred;

    // The cross image.
    dred_image* pImageCross;


    // The auto-generated variable declarations. You can find these in dred_autogenerated.h
    DRED_CONFIG_VARIABLE_DECLARATIONS

} dred_config;

typedef void (* dred_config_on_error_proc)(dred_config* pConfig, const char* configPath, const char* message, unsigned int line, void* pUserData);

bool dred_config_init(dred_config* pConfig, dred_context* pDred);
void dred_config_uninit(dred_config* pConfig);

// The pUserData argument of onError will be set to pConfig.
bool dred_config_load_file(dred_config* pConfig, const char* filePath, dred_config_on_error_proc onError, void* pUserData);

