// This file was automatically generated by the pre-build tool. Do not modify.

#define DRED_STOCK_IMAGE_ID_CROSS 0
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT 1
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT_DOWN 2


#define DRED_CONFIG_VARIABLE_DECLARATIONS \
bool showTabBar; \
bool showMenuBar; \
bool autoHideCmdBar; \
int windowWidth; \
int windowHeight; \
bool windowMaximized; \
float uiScale; \
dred_font* pUIFont; \
drgui_color cmdbarBGColor; \
drgui_color cmdbarBGColorActive; \
dred_font* pCmdbarTBFont; \
drgui_color cmdbarTBTextColor; \
float cmdbarPaddingX; \
float cmdbarPaddingY; \
drgui_color tabgroupBGColor; \
drgui_color tabBGColorInvactive; \
drgui_color tabBGColorActive; \
drgui_color tabBGColorHovered; \
dred_font* tabFont; \
drgui_color tabTextColor; \
drgui_color tabTextColorActive; \
drgui_color tabTextColorHovered; \
float tabPadding; \
bool tabShowCloseButton; \
drgui_color tabCloseButtonColor; \
dred_font* pTextEditorFont; \
drgui_color textEditorTextColor; \
drgui_color textEditorBGColor; \
drgui_color textEditorCursorColor; \
float textEditorCursorWidth; \
drgui_color textEditorSelectionBGColor; \
drgui_color textEditorActiveLineColor; \
bool textEditorShowLineNumbers; \
drgui_color textEditorLineNumbersColor; \
drgui_color textEditorLineNumbersBGColor; \
float textEditorLineNumbersPadding; \
drgui_color textEditorSBTrackColor; \
drgui_color textEditorSBThumbColor; \
drgui_color textEditorSBThumbColorHovered; \
drgui_color textEditorSBThumbColorPressed; \
float textEditorSBSize; \
bool textEditorShowScrollbarHorz; \
bool textEditorShowScrollbarVert; \
bool textEditorEnableExcessScrolling; \
bool textEditorTabsToSpacesEnabled; \
int textEditorTabSizeInSpaces; \
float textEditorScale;
