// This file was automatically generated by the pre-build tool. Do not modify.

#define DRED_STOCK_IMAGE_ID_CROSS 0
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT 1
#define DRED_STOCK_IMAGE_ID_ARROW_RIGHT_DOWN 2


#define DRED_CONFIG_VARIABLE_DECLARATIONS \
float uiScale; \
dred_font* pUIFont; \
drgui_color cmdbarBGColor; \
dred_font* pCmdbarTBFont; \
dred_font* pCmdbarMessageFont; \
float cmdbarPaddingX; \
float cmdbarPaddingY; \
drgui_color tabgroupBGColor; \
dred_font* pTextEditorFont; \
drgui_color textEditorBGColor; \
drgui_color textEditorActiveLineColor;